---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by user.
--- DateTime: 2022/8/2 20:53
---
LuaLauncher = {}

require("Utils")

local isEditor = CS.UnityEngine.Application.isEditor

function start()
    print("lua start...")
    print(Utils.max(10,20))
end

function update()
    print("1")
end

function fixUpdate()
    
end

function lateUpdate()
    
end

function destroy()
    print("lua destroyed.")
end